FROM {{ base_image }}:{{ base_distro_tag }}
MAINTAINER {{ maintainer }}

LABEL kolla_version="{{ kolla_version }}"

{{ include_header }}

ENV KOLLA_BASE_DISTRO {{ base_distro }}
ENV KOLLA_INSTALL_TYPE {{ install_type }}
ENV KOLLA_INSTALL_METATYPE {{ install_metatype }}


{% if base_distro in ['fedora', 'centos', 'oraclelinux', 'rhel'] %}
    {% if base_distro == 'centos' %}

RUN yum -y install epel-release \
    && rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7 \
    && yum -y install ansible \
    && yum clean all

    {% elif base_distro == 'oraclelinux' %}

RUN rpm -Uvh --nodeps http://mirror.centos.org/centos-7/7/extras/x86_64/Packages/epel-release-7-5.noarch.rpm \
    && rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7 \
    && yum -y install ansible \
    && yum clean all

    {% endif %}
{% elif base_distro in ['ubuntu', 'debian'] %}

# This will prevent questions from being asked during the install
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update \
    && apt-get -y install --no-install-recommends software-properties-common \
    && apt-add-repository -y ppa:ansible/ansible \
    && apt-get update \
    && apt-get -y install --no-install-recommends \
        ansible \
        aptitude \
        python-apt \
    && apt-get clean

{% endif %}

COPY playbooks /tmp/playbooks

RUN ansible-playbook -i localhost, -c local \
        -e supported_distro_release={{ supported_distro_release }} \
        -e install_type={{ install_type }} /tmp/playbooks/site.yml

CMD ["kolla_start"]
