- fail: "Only supported {{ supported_distro_release }} release on {{ base_distro }}"
  when: "{{ ansible_distribution_version }} != {{ supported_distro_release }}"

- copy: src=sources.list.{{ ansible_distribution }} dest=/etc/apt/sources.list
- copy: src=apt_preferences.{{ ansible_distribution }} dest=/etc/apt/preferences

- apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: "{{ item }}"
  when: ansible_distribution == 'Ubuntu'
  with_items:
    - 199369E5404BD5FC7D2FE43BCBCB082A1BB943DB
    - 391A9AA2147192839E9DB0315EDB1B62EC4926EA
    - 430BDF5C56E7C94E848EE60C1C4CBDCDCD2EFD2A
    - 08B73419AC32B4E966C1A330E84AC2C0460F3994
    - 46095ACC8548582C1A2699A9D27D666CD88E42B4
    - 58118E89F3A912897C070ADBF76221572C52609D

- apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: "{{ item }}"
  when: ansible_distribution == 'Debian'
  with_items:
    - 08B73419AC32B4E966C1A330E84AC2C0460F3994
    - 58118E89F3A912897C070ADBF76221572C52609D
    - "0xcbcb082a1bb943db"
    - D27D666CD88E42B4

- apt: update_cache=yes

- apt: upgrade=yes

- apt: upgrade=dist

- apt: name={{ item }}
  when: ansible_distribution == "Debian"
  with_items:
    - sudo

- apt: name={{ item }}
  with_items:
    - ca-certificates
    - curl
    - lvm2
    - open-iscsi
    - python
    - tgt

- shell: |
    sed -i "s|'purelib': '\$base/local/lib/python\$py_version_short/dist-packages',|'purelib': '\$base/lib/python\$py_version_short/dist-packages',|;s|'platlib': '\$platbase/local/lib/python\$py_version_short/dist-packages',|'platlib': '\$platbase/lib/python\$py_version_short/dist-packages',|;s|'headers': '\$base/local/include/python\$py_version_short/\$dist_name',|'headers': '\$base/include/python\$py_version_short/\$dist_name',|;s|'scripts': '\$base/local/bin',|'scripts': '\$base/bin',|;s|'data'   : '\$base/local',|'data'   : '\$base',|" /usr/lib/python2.7/distutils/command/install.py
  when: ansible_distribution == 'Ubuntu'

- file: path=/usr/lib/python2.7/site-packages state=absent

- file: src=/usr/lib/python2.7/dist-packages dest=/usr/lib/python2.7/site-packages state=link
