- fail: "Only supported {{ supported_distro_release }} release on {{ ansible_distribution }}"
  when: "{{ ansible_distribution_major_version }} != {{ supported_distro_release }}"

- include: "{{ ansible_os_family }}_{{ ansible_distribution }}.yml"

- yum_repository:
    name: elasticsearch-2.x
    description: Elasticsearch repository for 2.x packages
    baseurl: http://packages.elastic.co/elasticsearch/2.x/centos
    gpgcheck: yes
    gpgkey: http://packages.elastic.co/GPG-KEY-elasticsearch
    enabled: yes

- yum_repository:
    name: kibana-4.4
    description: Kibana repository for 4.4.x packages
    baseurl: http://packages.elastic.co/kibana/4.4/centos
    gpgcheck: yes
    gpgkey: http://packages.elastic.co/GPG-KEY-elasticsearch
    enabled: yes

- yum_repository:
    name: mariadb
    description: MariaDB
    baseurl: http://yum.mariadb.org/10.0/centos7-amd64
    gpgkey: http://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: yes

- name: delorean repo
  get_url: url=http://buildlogs.centos.org/centos/7/cloud/x86_64/rdo-trunk-master-tested/delorean.repo dest=/etc/yum.repos.d/delorean.repo

- name: delorean deps repo
  get_url: url=http://trunk.rdoproject.org/centos7/delorean-deps.repo dest=/etc/yum.repos.d/delorean-deps.repo

- yum: name=http://repo.percona.com/release/7/RPMS/x86_64/percona-release-0.1-3.noarch.rpm

- yum:
    name: "{{ item }}"
  with_items:
    - yum-plugin-priorities

- name: Copy the versionlock.list file
  copy: src=versionlock.list dest=/etc/yum/pluginconf.d/versionlock.list

- name: Upgrade the system
  yum: name=* state=latest

- name: Install common packages
  yum:
    name: "{{ item }}"
  with_items:
    - sudo
    - which
    - lvm2
    - scsi-target-utils
    - iscsi-initiator-utils

- name: Install packages for source install type
  yum:
    name: "{{ item }}"
  when: install_type == "source"
  with_items:
    - curl
    - tar
