- yum_repository:
    name: extras
    description: CentOS-$releasever - Extras
    mirrorlist: http://mirrorlist.centos.org/?release=7&arch=$basearch&repo=extras&infra=$infra
    gpgcheck: yes
    gpgkey: http://mirror.centos.org/centos/RPM-GPG-KEY-CentOS-7

- command: "rpm -Uvh --nodeps {{ item }}"
  with_items:
    - http://mirror.centos.org/centos-7/7/extras/x86_64/Packages/centos-release-ceph-hammer-1.0-5.el7.centos.noarch.rpm
    - http://mirror.centos.org/centos-7/7/extras/x86_64/Packages/centos-release-qemu-ev-1.0-1.el7.noarch.rpm
    - http://mirror.centos.org/centos-7/7/extras/x86_64/Packages/centos-release-virt-common-1-1.el7.centos.noarch.rpm
    - http://mirror.centos.org/centos-7/7/extras/x86_64/Packages/centos-release-storage-common-1-2.el7.centos.noarch.rpm

- find: path=/etc/yum.repos.d pattern='CentOS-*.repo'
  register: centos_repos

- replace: 
    dest: "{{ item.path }}"
    regexp: "^(.+)\\$releasever(.+)$"
    replace: "\\g<1>7\\2"
  with_items: "{{ centos_repos.files }}"

- rpm_key: key={{ item }}
  with_items:
    - /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
    - /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-Storage
    - /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-Virtualization

- command: yum-config-manager --enable ol7_optional_latest ol7_addons

